language: node_js
sudo: true
node_js: 6
script:
- npm run build
- npm run lint
- npm run codecov
deploy:
  edge: true
  provider: bluemixcloudfoundry
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  manifest: manifest.yml
  api: https://api.ng.bluemix.net 
  on:
    repo: melissaking720/social-customer-care
    branch: master
  skip_cleanup: true
